version: '2'
services:
  postgres-13.2:
    image: postgres:13.2
    container_name: postgres-docker-instance
    ports:
      - "5433:5432"
    # volumes: * Here you can indicate a volume path on local
    #   - ~/Documents/Developments/DbDocker/data/postgres-13.2:/var/lib/postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    restart: always  